swagger: "2.0"
info:
  title: Security Example Calc API
  description: This API demonstrates the use of the goa security plugin
  termsofservice: ""
  contact: null
  license: null
  version: ""
  extensions: {}
host: localhost:8080
basepath: ""
schemes: []
consumes: []
produces: []
paths:
  /add/{a}/{b}:
    ref: ""
    get:
      tags:
      - calc
      summary: add calc
      description: |-
        Add adds up the two integer parameters and returns the results. This endpoint is secured with the JWT scheme

        Required security scopes:
          * `calc:add`

        Required security scopes:
          * `calc:add`
      externaldocs: null
      operationid: calc#add
      consumes: []
      produces: []
      parameters:
      - name: a
        in: path
        description: Left operand
        required: true
        schema: null
        type: integer
        format: ""
        allowemptyvalue: false
        items: null
        collectionformat: ""
        default: null
        maximum: null
        exclusivemaximum: false
        minimum: null
        exclusiveminimum: false
        maxlength: null
        minlength: null
        pattern: ""
        maxitems: null
        minitems: null
        uniqueitems: false
        enum: []
        multipleof: 0
        extensions: {}
      - name: b
        in: path
        description: Right operand
        required: true
        schema: null
        type: integer
        format: ""
        allowemptyvalue: false
        items: null
        collectionformat: ""
        default: null
        maximum: null
        exclusivemaximum: false
        minimum: null
        exclusiveminimum: false
        maxlength: null
        minlength: null
        pattern: ""
        maxitems: null
        minitems: null
        uniqueitems: false
        enum: []
        multipleof: 0
        extensions: {}
      responses:
        "200":
          description: OK response.
          schema:
            schema: ""
            id: ""
            title: ""
            type: integer
            items: null
            properties: {}
            definitions: {}
            description: ""
            defaultvalue: null
            example: null
            media: null
            readonly: false
            pathstart: ""
            links: []
            ref: ""
            enum: []
            format: int64
            pattern: ""
            minimum: null
            maximum: null
            minlength: null
            maxlength: null
            required: []
            additionalproperties: false
            anyof: []
          headers: {}
          ref: ""
          extensions: {}
        "401":
          description: Unauthorized response.
          schema:
            schema: ""
            id: ""
            title: ""
            type: integer
            items: null
            properties: {}
            definitions: {}
            description: ""
            defaultvalue: null
            example: null
            media: null
            readonly: false
            pathstart: ""
            links: []
            ref: ""
            enum: []
            format: int64
            pattern: ""
            minimum: null
            maximum: null
            minlength: null
            maxlength: null
            required: []
            additionalproperties: false
            anyof: []
          headers: {}
          ref: ""
          extensions: {}
      schemes:
      - http
      deprecated: false
      security:
      - jwt: []
      extensions: {}
    put: null
    post: null
    delete: null
    options: null
    head: null
    patch: null
    parameters: []
    extensions: {}
  /login:
    ref: ""
    get: null
    put: null
    post:
      tags:
      - calc
      summary: login calc
      description: Creates a valid JWT
      externaldocs: null
      operationid: calc#login
      consumes: []
      produces: []
      parameters:
      - name: LoginRequestBody
        in: body
        description: ""
        required: true
        schema:
          schema: ""
          id: ""
          title: ""
          type: ""
          items: null
          properties: {}
          definitions: {}
          description: ""
          defaultvalue: null
          example: null
          media: null
          readonly: false
          pathstart: ""
          links: []
          ref: '#/definitions/LoginRequestBody'
          enum: []
          format: ""
          pattern: ""
          minimum: null
          maximum: null
          minlength: null
          maxlength: null
          required: []
          additionalproperties: false
          anyof: []
        type: ""
        format: ""
        allowemptyvalue: false
        items: null
        collectionformat: ""
        default: null
        maximum: null
        exclusivemaximum: false
        minimum: null
        exclusiveminimum: false
        maxlength: null
        minlength: null
        pattern: ""
        maxitems: null
        minitems: null
        uniqueitems: false
        enum: []
        multipleof: 0
        extensions: {}
      responses:
        "200":
          description: OK response.
          schema:
            schema: ""
            id: ""
            title: ""
            type: string
            items: null
            properties: {}
            definitions: {}
            description: ""
            defaultvalue: null
            example: null
            media: null
            readonly: false
            pathstart: ""
            links: []
            ref: ""
            enum: []
            format: ""
            pattern: ""
            minimum: null
            maximum: null
            minlength: null
            maxlength: null
            required: []
            additionalproperties: false
            anyof: []
          headers: {}
          ref: ""
          extensions: {}
        "401":
          description: Unauthorized response.
          schema:
            schema: ""
            id: ""
            title: ""
            type: ""
            items: null
            properties: {}
            definitions: {}
            description: ""
            defaultvalue: null
            example: null
            media: null
            readonly: false
            pathstart: ""
            links: []
            ref: '#/definitions/LoginUnauthorizedResponseBody'
            enum: []
            format: ""
            pattern: ""
            minimum: null
            maximum: null
            minlength: null
            maxlength: null
            required: []
            additionalproperties: false
            anyof: []
          headers: {}
          ref: ""
          extensions: {}
      schemes:
      - http
      deprecated: false
      security:
      - basic: []
      extensions: {}
    delete: null
    options: null
    head: null
    patch: null
    parameters: []
    extensions: {}
definitions:
  LoginRequestBody:
    schema: ""
    id: ""
    title: LoginRequestBody
    type: object
    items: null
    properties:
      password:
        schema: ""
        id: ""
        title: ""
        type: string
        items: null
        properties: {}
        definitions: {}
        description: ""
        defaultvalue: null
        example: password
        media: null
        readonly: false
        pathstart: ""
        links: []
        ref: ""
        enum: []
        format: ""
        pattern: ""
        minimum: null
        maximum: null
        minlength: null
        maxlength: null
        required: []
        additionalproperties: false
        anyof: []
      user:
        schema: ""
        id: ""
        title: ""
        type: string
        items: null
        properties: {}
        definitions: {}
        description: ""
        defaultvalue: null
        example: username
        media: null
        readonly: false
        pathstart: ""
        links: []
        ref: ""
        enum: []
        format: ""
        pattern: ""
        minimum: null
        maximum: null
        minlength: null
        maxlength: null
        required: []
        additionalproperties: false
        anyof: []
    definitions: {}
    description: Credentials used to authenticate to retrieve JWT token
    defaultvalue: null
    example:
      password: password
      user: username
    media: null
    readonly: false
    pathstart: ""
    links: []
    ref: ""
    enum: []
    format: ""
    pattern: ""
    minimum: null
    maximum: null
    minlength: null
    maxlength: null
    required:
    - user
    - password
    additionalproperties: false
    anyof: []
  LoginUnauthorizedResponseBody:
    schema: ""
    id: ""
    title: LoginUnauthorizedResponseBody
    type: string
    items: null
    properties: {}
    definitions: {}
    description: Credentials are invalid
    defaultvalue: null
    example: Optio doloremque.
    media: null
    readonly: false
    pathstart: ""
    links: []
    ref: ""
    enum: []
    format: ""
    pattern: ""
    minimum: null
    maximum: null
    minlength: null
    maxlength: null
    required: []
    additionalproperties: false
    anyof: []
parameters: {}
responses: {}
securitydefinitions:
  basic:
    type: basic
    description: Secures the login endpoint.
    name: ""
    in: ""
    flow: ""
    authorizationurl: ""
    tokenurl: ""
    scopes: {}
    extensions: {}
  jwt:
    type: apiKey
    description: |-
      Secures endpoint by requiring a valid JWT token retrieved via the login endpoint. Supports scope "calc:add".
      **Security Scopes**:
        * `calc:add`: Allows performing additions
    name: Authorization
    in: header
    flow: ""
    authorizationurl: ""
    tokenurl: ""
    scopes: {}
    extensions: {}
tags: []
externaldocs:
  description: Security example README
  url: https://github.com/goadesign/plugins/security/tree/master/example/README.md
