swagger: "2.0"
info:
  title: Security Example Calc API
  description: This API demonstrates the use of the goa security plugin
  termsofservice: ""
  contact: null
  license: null
  version: ""
  extensions: {}
host: localhost:8080
basepath: ""
schemes: []
consumes: []
produces: []
paths:
  /add/{a}/{b}:
    ref: ""
    get:
      tags:
      - calc
      summary: add calc
      description: |-
        Add adds up the two integer parameters and returns the results. This endpoint is secured with the JWT scheme

        Required security scopes:
          * `calc:add`
      externaldocs: null
      operationid: calc#add
      consumes: []
      produces: []
      parameters:
      - name: a
        in: path
        description: Left operand
        required: true
        schema: null
        type: integer
        format: ""
        allowemptyvalue: false
        items: null
        collectionformat: ""
        default: null
        maximum: null
        exclusivemaximum: false
        minimum: null
        exclusiveminimum: false
        maxlength: null
        minlength: null
        pattern: ""
        maxitems: null
        minitems: null
        uniqueitems: false
        enum: []
        multipleof: 0
        extensions: {}
      - name: b
        in: path
        description: Right operand
        required: true
        schema: null
        type: integer
        format: ""
        allowemptyvalue: false
        items: null
        collectionformat: ""
        default: null
        maximum: null
        exclusivemaximum: false
        minimum: null
        exclusiveminimum: false
        maxlength: null
        minlength: null
        pattern: ""
        maxitems: null
        minitems: null
        uniqueitems: false
        enum: []
        multipleof: 0
        extensions: {}
      responses:
        "200":
          description: OK response.
          schema:
            schema: ""
            id: ""
            title: ""
            type: integer
            items: null
            properties: {}
            definitions: {}
            description: ""
            defaultvalue: null
            example: null
            media: null
            readonly: false
            pathstart: ""
            links: []
            ref: ""
            enum: []
            format: int64
            pattern: ""
            minimum: null
            maximum: null
            minlength: null
            maxlength: null
            required: []
            additionalproperties: false
            anyof: []
          headers: {}
          ref: ""
          extensions: {}
        "403":
          description: Forbidden response.
          schema:
            schema: ""
            id: ""
            title: ""
            type: ""
            items: null
            properties: {}
            definitions: {}
            description: ""
            defaultvalue: null
            example: null
            media: null
            readonly: false
            pathstart: ""
            links: []
            ref: '#/definitions/AddForbiddenResponseBody'
            enum: []
            format: ""
            pattern: ""
            minimum: null
            maximum: null
            minlength: null
            maxlength: null
            required: []
            additionalproperties: false
            anyof: []
          headers: {}
          ref: ""
          extensions: {}
      schemes:
      - http
      deprecated: false
      security:
      - jwt: []
      extensions: {}
    put: null
    post: null
    delete: null
    options: null
    head: null
    patch: null
    parameters: []
    extensions: {}
  /login:
    ref: ""
    get: null
    put: null
    post:
      tags:
      - calc
      summary: login calc
      description: Creates a valid JWT
      externaldocs: null
      operationid: calc#login
      consumes: []
      produces: []
      parameters: []
      responses:
        "200":
          description: OK response.
          schema:
            schema: ""
            id: ""
            title: ""
            type: string
            items: null
            properties: {}
            definitions: {}
            description: ""
            defaultvalue: null
            example: null
            media: null
            readonly: false
            pathstart: ""
            links: []
            ref: ""
            enum: []
            format: ""
            pattern: ""
            minimum: null
            maximum: null
            minlength: null
            maxlength: null
            required: []
            additionalproperties: false
            anyof: []
          headers: {}
          ref: ""
          extensions: {}
        "401":
          description: Unauthorized response.
          schema:
            schema: ""
            id: ""
            title: ""
            type: ""
            items: null
            properties: {}
            definitions: {}
            description: ""
            defaultvalue: null
            example: null
            media: null
            readonly: false
            pathstart: ""
            links: []
            ref: '#/definitions/LoginUnauthorizedResponseBody'
            enum: []
            format: ""
            pattern: ""
            minimum: null
            maximum: null
            minlength: null
            maxlength: null
            required: []
            additionalproperties: false
            anyof: []
          headers: {}
          ref: ""
          extensions: {}
      schemes:
      - http
      deprecated: false
      security:
      - basic: []
      extensions: {}
    delete: null
    options: null
    head: null
    patch: null
    parameters: []
    extensions: {}
definitions:
  AddForbiddenResponseBody:
    schema: ""
    id: ""
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    items: null
    properties:
      id:
        schema: ""
        id: ""
        title: ""
        type: string
        items: null
        properties: {}
        definitions: {}
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        defaultvalue: null
        example: 123abc
        media: null
        readonly: false
        pathstart: ""
        links: []
        ref: ""
        enum: []
        format: ""
        pattern: ""
        minimum: null
        maximum: null
        minlength: null
        maxlength: null
        required: []
        additionalproperties: false
        anyof: []
      message:
        schema: ""
        id: ""
        title: ""
        type: string
        items: null
        properties: {}
        definitions: {}
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        defaultvalue: null
        example: parameter 'p' must be an integer
        media: null
        readonly: false
        pathstart: ""
        links: []
        ref: ""
        enum: []
        format: ""
        pattern: ""
        minimum: null
        maximum: null
        minlength: null
        maxlength: null
        required: []
        additionalproperties: false
        anyof: []
      name:
        schema: ""
        id: ""
        title: ""
        type: string
        items: null
        properties: {}
        definitions: {}
        description: Name is the name of this class of errors.
        defaultvalue: null
        example: bad_request
        media: null
        readonly: false
        pathstart: ""
        links: []
        ref: ""
        enum: []
        format: ""
        pattern: ""
        minimum: null
        maximum: null
        minlength: null
        maxlength: null
        required: []
        additionalproperties: false
        anyof: []
      temporary:
        schema: ""
        id: ""
        title: ""
        type: boolean
        items: null
        properties: {}
        definitions: {}
        description: Is the error temporary?
        defaultvalue: null
        example: false
        media: null
        readonly: false
        pathstart: ""
        links: []
        ref: ""
        enum: []
        format: ""
        pattern: ""
        minimum: null
        maximum: null
        minlength: null
        maxlength: null
        required: []
        additionalproperties: false
        anyof: []
      timeout:
        schema: ""
        id: ""
        title: ""
        type: boolean
        items: null
        properties: {}
        definitions: {}
        description: Is the error a timeout?
        defaultvalue: null
        example: true
        media: null
        readonly: false
        pathstart: ""
        links: []
        ref: ""
        enum: []
        format: ""
        pattern: ""
        minimum: null
        maximum: null
        minlength: null
        maxlength: null
        required: []
        additionalproperties: false
        anyof: []
    definitions: {}
    description: AddForbiddenResponseBody result type (default view)
    defaultvalue: null
    example:
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    media: null
    readonly: false
    pathstart: ""
    links: []
    ref: ""
    enum: []
    format: ""
    pattern: ""
    minimum: null
    maximum: null
    minlength: null
    maxlength: null
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    additionalproperties: false
    anyof: []
  LoginUnauthorizedResponseBody:
    schema: ""
    id: ""
    title: LoginUnauthorizedResponseBody
    type: string
    items: null
    properties: {}
    definitions: {}
    description: Credentials are invalid
    defaultvalue: null
    example: Quis aliquid architecto facere.
    media: null
    readonly: false
    pathstart: ""
    links: []
    ref: ""
    enum: []
    format: ""
    pattern: ""
    minimum: null
    maximum: null
    minlength: null
    maxlength: null
    required: []
    additionalproperties: false
    anyof: []
parameters: {}
responses: {}
securitydefinitions:
  basic:
    type: basic
    description: Secures the login endpoint.
    name: ""
    in: ""
    flow: ""
    authorizationurl: ""
    tokenurl: ""
    scopes: {}
    extensions: {}
  jwt:
    type: apiKey
    description: |-
      Secures endpoint by requiring a valid JWT token retrieved via the login endpoint. Supports scope "calc:add".
      **Security Scopes**:
        * `calc:add`: Allows performing additions
    name: Authorization
    in: header
    flow: ""
    authorizationurl: ""
    tokenurl: ""
    scopes: {}
    extensions: {}
tags: []
externaldocs:
  description: Security example README
  url: https://github.com/goadesign/plugins/security/tree/master/example/README.md
